/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface IncomeDocument {
  date: string | null;
  id: Generated<number | null>;
  partner_id: number | null;
  posted: Generated<number | null>;
}

export interface IncomeDocumentItem {
  document_id: number | null;
  id: Generated<number | null>;
  price: Generated<number>;
  product_id: number | null;
  quantity: Generated<number>;
}

export interface Partner {
  id: Generated<number>;
  name: string;
}

export interface PriceSettingDocument {
  date: string | null;
  id: Generated<number | null>;
  posted: Generated<number | null>;
}

export interface PriceSettingDocumentItem {
  document_id: number | null;
  id: Generated<number | null>;
  price: Generated<number>;
  product_id: number | null;
}

export interface Product {
  article: Generated<string>;
  brand: Generated<string>;
  description: Generated<string>;
  id: Generated<number>;
  name: Generated<string>;
  nameAlt: Generated<string>;
  oem: Generated<string>;
  photos: Generated<string>;
  places: Generated<string>;
  units: Generated<string>;
}

export interface ProductPrice {
  id: Generated<number | null>;
  price: Generated<number>;
  product_id: number | null;
  timestamp: string;
}

export interface ProductPriceLatest {
  price: number | null;
  product_id: number | null;
}

export interface ProductStock {
  document_id: number;
  id: Generated<number | null>;
  product_id: number | null;
  quantity: number;
  timestamp: string;
}

export interface SalesDocument {
  date: string | null;
  id: Generated<number>;
  partner_id: number | null;
  posted: Generated<number | null>;
}

export interface SalesDocumentItem {
  created_at: Generated<string>;
  document_id: number;
  id: Generated<number | null>;
  price: Generated<number>;
  product_id: number;
  quantity: Generated<number>;
}

export interface DB {
  income_document: IncomeDocument;
  income_document_item: IncomeDocumentItem;
  partner: Partner;
  price_setting_document: PriceSettingDocument;
  price_setting_document_item: PriceSettingDocumentItem;
  product: Product;
  product_price: ProductPrice;
  product_price_latest: ProductPriceLatest;
  product_stock: ProductStock;
  sales_document: SalesDocument;
  sales_document_item: SalesDocumentItem;
}
